# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: KsplDev.Net8TestApp
PackageVersion: 1.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: Net8TestApp.exe
Installers:
- InstallerUrl: https://github.com/KsplDev/Net8TestApp/releases/download/TestRelease/Net8TestApp.zip
  Architecture: x64
  InstallerSha256: 6FABAE8E19E5BB1A38C3D5BCA196FF746815CDCF8E92360509DEEE4F5E77C83F
ManifestType: installer
ManifestVersion: 1.6.0
